import { db } from '@/db';
import { tasks } from '@/db/schema';

async function main() {
    const now = new Date();
    const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
    const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
    const threeDaysFromNow = new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000);
    const fiveDaysFromNow = new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000);
    const oneWeekFromNow = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
    const tenDaysFromNow = new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000);
    const twoWeeksFromNow = new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000);
    const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);
    const oneWeekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    const twoWeeksAgo = new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000);

    const sampleTasks = [
        {
            userId: "1",
            title: 'Prepare quarterly report',
            description: 'Compile Q1 financial data and create presentation for board meeting',
            priority: 'high',
            startDate: now.toISOString(),
            dueDate: threeDaysFromNow.toISOString(),
            category: 'work',
            status: 'in_progress',
            archived: false,
            googleCalendarEventId: null,
            createdAt: twoWeeksAgo.toISOString(),
            updatedAt: now.toISOString(),
        },
        {
            userId: "1",
            title: 'Schedule dentist appointment',
            description: null,
            priority: 'low',
            startDate: null,
            dueDate: oneWeekFromNow.toISOString(),
            category: 'personal',
            status: 'upcoming',
            archived: false,
            googleCalendarEventId: null,
            createdAt: fiveDaysFromNow.toISOString(),
            updatedAt: fiveDaysFromNow.toISOString(),
        },
        {
            userId: "2",
            title: 'Review project proposal',
            description: 'Review and provide feedback on the new mobile app proposal from the design team',
            priority: 'medium',
            startDate: twoDaysAgo.toISOString(),
            dueDate: yesterday.toISOString(),
            category: 'work',
            status: 'overdue',
            archived: false,
            googleCalendarEventId: null,
            createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: yesterday.toISOString(),
        },
        {
            userId: "2",
            title: 'Team meeting at 2 PM',
            description: 'Weekly sync with the development team to discuss sprint progress',
            priority: 'high',
            startDate: now.toISOString(),
            dueDate: now.toISOString(),
            category: 'work',
            status: 'in_progress',
            archived: false,
            googleCalendarEventId: 'evt_abc123def456',
            createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: now.toISOString(),
        },
        {
            userId: "1",
            title: 'Submit expense reports',
            description: null,
            priority: 'medium',
            startDate: tomorrow.toISOString(),
            dueDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'work',
            status: 'upcoming',
            archived: false,
            googleCalendarEventId: null,
            createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: "3",
            title: 'Call client about feedback',
            description: 'Follow up with Johnson & Co regarding their feedback on the latest prototype',
            priority: 'high',
            startDate: now.toISOString(),
            dueDate: tomorrow.toISOString(),
            category: 'urgent',
            status: 'upcoming',
            archived: false,
            googleCalendarEventId: null,
            createdAt: now.toISOString(),
            updatedAt: now.toISOString(),
        },
        {
            userId: "1",
            title: 'Gym session',
            description: null,
            priority: 'low',
            startDate: null,
            dueDate: fiveDaysFromNow.toISOString(),
            category: 'health',
            status: 'upcoming',
            archived: false,
            googleCalendarEventId: null,
            createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: "2",
            title: 'Read industry articles',
            description: null,
            priority: 'medium',
            startDate: null,
            dueDate: oneWeekFromNow.toISOString(),
            category: 'learning',
            status: 'upcoming',
            archived: false,
            googleCalendarEventId: null,
            createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: "3",
            title: 'Complete code review',
            description: 'Review pull requests for authentication module implementation',
            priority: 'medium',
            startDate: oneWeekAgo.toISOString(),
            dueDate: oneWeekAgo.toISOString(),
            category: 'work',
            status: 'completed',
            archived: false,
            googleCalendarEventId: null,
            createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: oneWeekAgo.toISOString(),
        },
        {
            userId: "1",
            title: 'Update project documentation',
            description: null,
            priority: 'medium',
            startDate: now.toISOString(),
            dueDate: new Date(now.getTime() + 4 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'work',
            status: 'in_progress',
            archived: false,
            googleCalendarEventId: null,
            createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: now.toISOString(),
        },
        {
            userId: "2",
            title: 'Prepare presentation slides',
            description: 'Create slides for client pitch meeting next week covering product roadmap and pricing',
            priority: 'high',
            startDate: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            dueDate: twoDaysAgo.toISOString(),
            category: 'work',
            status: 'overdue',
            archived: false,
            googleCalendarEventId: null,
            createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: yesterday.toISOString(),
        },
        {
            userId: "1",
            title: 'Morning meditation',
            description: null,
            priority: 'low',
            startDate: now.toISOString(),
            dueDate: now.toISOString(),
            category: 'personal',
            status: 'completed',
            archived: true,
            googleCalendarEventId: null,
            createdAt: now.toISOString(),
            updatedAt: now.toISOString(),
        },
        {
            userId: "3",
            title: 'Learn new framework tutorial',
            description: 'Complete Next.js 14 tutorial series on YouTube to learn app router and server components',
            priority: 'medium',
            startDate: threeDaysFromNow.toISOString(),
            dueDate: tenDaysFromNow.toISOString(),
            category: 'learning',
            status: 'upcoming',
            archived: false,
            googleCalendarEventId: null,
            createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: "2",
            title: 'Client status call',
            description: null,
            priority: 'high',
            startDate: yesterday.toISOString(),
            dueDate: yesterday.toISOString(),
            category: 'urgent',
            status: 'completed',
            archived: false,
            googleCalendarEventId: 'evt_xyz789ghi012',
            createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: yesterday.toISOString(),
        },
        {
            userId: "1",
            title: 'Plan team offsite',
            description: null,
            priority: 'medium',
            startDate: oneWeekFromNow.toISOString(),
            dueDate: twoWeeksFromNow.toISOString(),
            category: 'work',
            status: 'upcoming',
            archived: false,
            googleCalendarEventId: null,
            createdAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(tasks).values(sampleTasks);
    
    console.log('✅ Tasks seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});
